### ISSUE TITLE
Bump read-json dependency from npm-shrinkwrap@200.x

### ISSUE THREAD

**Issue by cristiandouce** [uber/npm-shrinkwrap#103]
https://github.com/uber/npm-shrinkwrap/blob/v200.5.0/package.json#L21

This is causing installation errors since it seems that all versions prior to `1.x` for `read-json` dissapeared from the npm registry.

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "npm-shrinkwrap@200.4.0"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! version not found: read-json@0.1.0
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by jfromaniello** [comment]
[I've Just Liberated All My Modules](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c). 

read-json is on his list

**Comment by as19git67** [comment]
Please accept the pull request to increase read-json version and publish to npm registry. Thank you.

**Comment by bmatusiak** [comment]
+1, Breaking builds

**Comment by mroderick** [comment]
You can also just merge https://github.com/uber/npm-shrinkwrap/pull/102, which uses the same `read-json` version that is already in the `master` branch of this repository.

**Comment by cristiandouce** [comment]
It appears there is a new release `200.5.1` already that fixes this issue. :fried_shrimp:
