### ISSUE TITLE
Can't shrinkwrap npm-shrinkwrap on NPM 2

### ISSUE THREAD

**Issue by habibalamin** [uber/npm-shrinkwrap#68]
Because of NPM 2's upgrade to semver 4, and npm-shrinkwrap's dependency on a package that depends on two other packages that have semver 4 incompatible versions, you cannot shrinkwrap npm-shrinkwrap on NPM 2. This is the issue as far as I can see.

Here's the relevant cross-section of `npm list` output.

```
  │ ├─┬ sha@1.2.4
  │ │ └─┬ readable-stream@1.0.27-1 invalid
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.25-1 invalid
```

**Comment by Raynos** [comment]
There is a version 200 of `npm-shrinkwrap` that you can use with npm 2.

Try using that instead.

**Comment by habibalamin** [comment]
So, I've edcided to use npm-lockdown in the meantime, which says in the README:

>At present (as of npm v1.1.33), the implementation of shrinkwrap has a couple flaws
which make it unusable for certain applications:

>  1. No checksums! NPM shrinkwrap does not guarantee bit-wise equality of the installed
     dependencies, so if an upstream server or author decides to change the contents of
     version 1.2.3 of `foo`, you'll install something different than you intended without
     knowing.
>  2. Does not play nice with `optionalDependencies` - If you "shrinkwrap" your app and you
     have an installed dep that is optional, the dependency is no longer optional.  This might
     not be what you want.

>  [npm shrinkwrap]: https://npmjs.org/doc/shrinkwrap.html

How are we doing with those, especially optionalDependencies? I consider my problem solved, but just curious for the future.

**Comment by Raynos** [comment]
`optionalDependencies` are not a thing. You shrinkwrap applications.

Your application does not have optional dependencies.

As for the checksums; yep we dont have any checksums. We just assume our internal mirror is not corrupted. We have not had any issues yet.
