### ISSUE TITLE
Latest version on npmjs.com is 200.4.0?

### ISSUE THREAD

**Issue by dahjelle** [uber/npm-shrinkwrap#75]
…but `package.json` here on the master branch shows it at 5.4.0.

https://www.npmjs.com/package/npm-shrinkwrap

I assume 5.4.0 is the actual latest version?

**Comment by Raynos** [comment]
@dahjelle there is a 2.0 branch.

**Comment by dahjelle** [comment]
@Raynos Sure. Which version should be `@latest` on npm, then? Did the 2.0 branch get published by mistake, or is there something I'm missing?

**Comment by Raynos** [comment]
hmm; i should retag 5.4 as latest.

**Comment by Raynos** [comment]
retagged.

**Comment by dahjelle** [comment]
Awesome! Thanks! :-D
