### ISSUE TITLE
What is release v200.4.0?

### ISSUE THREAD

**Issue by bhamodi** [uber/npm-shrinkwrap#79]
I see in the releases section of this repo that there is a version 200 release that seems to have nothing different from v5.4.0. Should this be deleted?

**Comment by Raynos** [comment]
@bhamodi 

v200 depends on npm@2; v5 depends on npm@1

**Comment by bhamodi** [comment]
Oh I see. So, the reason I'm asking this question is because when I run any sort of npm package updater, it checks and says the latest release is v5.4.0. Are there any plans to get around this?

**Comment by Raynos** [comment]
No. I have two concurrent majors and latest can only point to one thing. 

The npm updating tools have to get smarter

**Comment by bhamodi** [comment]
Closing this issue as this is out of our control.
