### ISSUE TITLE
EMFILE error when running shrinkwrap command

### ISSUE THREAD

**Issue by MarkRausch** [uber/npm-shrinkwrap#85]
When I run the shrinkwrap command I get the following error:
```mrausch-osx:sparkler-web mrausch$ ./node_modules/.bin/npm-shrinkwrap --dev
EMFILE, open '/Users/mrausch/Projects/sparkler-web/node_modules/node-libs-browser/node_modules/path-browserify/package.json'
something went wrong. Did not write npm-shrinkwrap.json```

As a workaround I bumped ulimit -n from 256 up to 2560 and the command runs successfully.

**Comment by Raynos** [comment]
That's expected behaviour.

**Comment by MarkRausch** [comment]
It's expected behavior that it fails unless you modify an individual system's configuration?

**Comment by Raynos** [comment]
I dont know who is the blame to it. I suspect it's our npm dependency and it's an npm bug. 

It could be npm-shrinkwrap itself in which case replacing `fs` with `graceful-fs` might fix it.

**Comment by MarkRausch** [comment]
Ok, thanks
