### ISSUE TITLE
Issues with node@4

### ISSUE THREAD

**Issue by cristiandouce** [uber/npm-shrinkwrap#89]
When doing `npm install -S npm-shrinkwrap` everything goes fine despite some warnings like:

```
npm WARN engine npm@1.4.21: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"4.2.1","npm":"2.14.7"})
```

But, when I run `npm ls`, at the bottom I found this:

```
npm ERR! invalid: readable-stream@1.0.27-1 $HOME/test/node_modules/npm-shrinkwrap/node_modules/npm/node_modules/sha/node_modules/readable-stream
npm ERR! invalid: string_decoder@0.10.25-1 $HOME/test/node_modules/npm-shrinkwrap/node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/string_decoder
```

The trouble here is that `npm-shrinkwrap` depends directly on `npm@1.4.21`.

Could it be bump to `npm@2` ?

**Comment by Raynos** [comment]
There exists a version of npm-shrinkwrap that uses npm@2.

It's `npm-shrinkwrap@200`. I created a branch thats npm@2 compatible and bumped major to 200.

**Comment by cristiandouce** [comment]
@Raynos right... that works.

Wasn't able to find it in the readme... worth adding it?

**Comment by Raynos** [comment]
Updated readme. Thanks!

**Comment by cristiandouce** [comment]
np, thank you!
